# .goreleaser.yml
# Build customization
builds:
  - main: cmd/tunacan/main.go
    binary: tunacan
    goos:
      - darwin
    goarch:
      - amd64
brew:
  github:
    owner: yokoe
    name: tunacan

  homepage: "https://github.com/yokoe/tunacan"

  install: |
    bin.install "tunacan"
